### ISSUE TITLE
Support Uuid identity

### ISSUE THREAD

**Issue by sylvainfilteau** [yvoyer/identity#12]

**Comment by yvoyer** [comment]
The uuid identity can be implemented in user-land using the `StringIdentity`.

```php
final class UUID Identity extends StringIdentity
{
    public function __construct(string $id) 
    {
        parent::__construct(UUID::fromString($id)->toString());
    }
}
```

I won't implement it to avoid adding a dependency to a specific uuid library. I recommend using the [uuid library](https://github.com/ramsey/uuid) to implement it on your app side.

Thank you for the suggestion.
